### ISSUE TITLE
Add All Glitch

### ISSUE THREAD

**Issue by lightsourced** [blaxxun-boop/ConversionSizeAndSpeed#2]
Thank you so much for adding the "Add All" feature, however, now when I have a large amount of resources in my inventory and click Shift+E to add all, it adds all the resources despite the limit dictated in the config.

Screenshots:
https://imgur.com/a/UEKClMv

**Comment by blaxxun-boop** [comment]
I can see how this could happen sometimes, if you aren't the owner of the smelter and the connection speed is slow in multiplayer. Shouldn't be possible anymore in v1.0.2.
