### ISSUE TITLE
Incompatibility with Aedenthorns Craft From Containers

### ISSUE THREAD

**Issue by B5tard** [blaxxun-boop/ConversionSizeAndSpeed#7]
When both yours and his mods are present, newly build kilns, smelters etc function fine. However when you exit and reload the game, they stay frozen, no longer processing ore or wood. If you break and rebuild, they will work until you exit and reload again. If you disable "craft from containers" then you can use your mod without issue, exit and reload without issue.  There is some sort of interaction between the two.. I am using the latest bepinX 5.4.21.0, as well.  

https://www.nexusmods.com/valheim/mods/40?tab=description currently version 3.1.2

**Comment by blaxxun-boop** [comment]
I don't support mods made by Aedenthorn, sorry. Please use any of the alternatives to crafting from containers. All the others work perfectly fine.

**Comment by B5tard** [comment]
such as?>

**Comment by B5tard** [comment]
tried the odin plus crafty boxes.. same issue.
