### ISSUE TITLE
No connection to dedicated server possible

### ISSUE THREAD

**Issue by Caaruzo** [blaxxun-boop/ConversionSizeAndSpeed#8]
Dedicated Server can't be joined anymore, with this mod active.
Happens after todays hotfix.

**Comment by blaxxun-boop** [comment]
There wasn't a hotfix today. Mod still works fine for the current version of 0.216.9.

You might be playing on the PTB and I cannot support my mods for the PTB. They are just too many and there are too many changes on the PTB to make sure that all my mods work on all PTB versions.

**Comment by Caaruzo** [comment]
Seen that wrong. Iam not on PTB but still dont work with mod activated on dedicated server. It always disconnects players. With only on client side it works.

**Comment by blaxxun-boop** [comment]
I've tested the mod on a dedicated server and it works perfectly fine.

Just check your log files to find the reason for your disconnects.

**Comment by Caaruzo** [comment]
Thats what happens in log, when trying to connect. Until yesterday it worked fine. We didn't change anything.

`07/22/2023 10:54:54: Failed to place all MountainCave02, placed 129 out of 160
07/22/2023 10:54:58:  Done generating locations, duration:56259.558 ms
07/22/2023 10:54:58: World db couldn't load correctly, saving has been disabled to prevent .old file from being overwritten.
The shader Hidden/Dof/DepthOfFieldHdr (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) is not supported on this platform!
The image effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) has been disabled as it's not supported on the current platform.
The shader Hidden/SunShaftsComposite (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
The shader Hidden/SimpleClear (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
The image effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) has been disabled as it's not supported on the current platform.
07/22/2023 10:54:58: Game server connected
07/22/2023 10:54:58: Game - OnApplicationQuit
07/22/2023 10:54:58: Shuting down
07/22/2023 10:54:58: ZNet Shutdown
07/22/2023 10:54:58: Skipping world save
07/22/2023 10:54:58: Unloading unused assets
07/22/2023 10:54:58: Sending disconnect msg
07/22/2023 10:54:58: Disposing socket
07/22/2023 10:54:58: Stopping listening socket
07/22/2023 10:54:58: Last socket, unregistering callback
07/22/2023 10:54:58: ZSteamSocket  UnregisterGlobalCallbacks, existing sockets:0
`

**Valheim Version:** 2023-05-16 0.216.9
**BepInEx Version:** 5.4.21.0

**Comment by Caaruzo** [comment]
Found something else, maybe that helps. Only happens with activated ConvenionSize Mod

[Error  : Unity Log] 07/22/2023 10:54:01: Exception while loading world /home/sid_5309377/valheim/.config/unity3d/IronGate/Valheim/worlds_local/world.db:System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at ZDOExtraData.Add (ZDOID zid, System.Int32 hash, System.String value) [0x00000] in <eecdcf8f395d4782a04ac4ff3fc6cb35>:0 
  at ConversionSizeSpeed.ZDOStuff+LoadZDO.Postfix (ZDO __instance) [0x00067] in <58c2caf0eaab45f3a0785c6c3d90787b>:0 
  at (wrapper dynamic-method) ZDO.DMD<ZDO::Load>(ZDO,ZPackage,int)
  at ZDOMan.Load (System.IO.BinaryReader reader, System.Int32 version) [0x00141] in <eecdcf8f395d4782a04ac4ff3fc6cb35>:0 
  at (wrapper dynamic-method) ZNet.DMD<ZNet::LoadWorld>(ZNet)

[Error  : Unity Log] 07/22/2023 10:54:01: World load failed mid-file. Exiting without save. Check backups!

**Comment by blaxxun-boop** [comment]
Yes, that helps a lot, thanks.

I've just pushed v1.0.13 to Thunderstore, with a workaround for this. And I really hope the first thing that Iron Gate does when they are back from their vacation is fixing their messed up world loading code.

**Comment by Caaruzo** [comment]
Awesome. I'll check that Version later then. Thx very much for your mod and your help.

**Comment by Caaruzo** [comment]
Works perfect. Thx very much.
