### ISSUE TITLE
Kiln stop working

### ISSUE THREAD

**Issue by Caaruzo** [blaxxun-boop/ConversionSizeAndSpeed#9]
Hi there. We setup the Kiln to hold 200 Fuel to convert it to charocal. We most time fill it up with shift+E.
Sometimes the Klin is stop working with fuel left in it. Only way to fix it, is to destroy and replace it.

What might be the cause of it? Is there an way to fix it? Thx much in advance.

**Comment by blaxxun-boop** [comment]
Should be fixed in v1.0.14.
